---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: minecraft-securitycraft01
spec:
  storageClassName: cephfs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
