apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: br0.20
  namespace: vm
  annotations:
    kubevirt.io/allow-pod-bridge-network-live-migration: "true"
spec:
  config: '{"cniVersion":"0.3.1","name":"br0.20","plugins":[{"type":"bridge","bridge":"br0.20","ipam":{}},{"type":"tuning"}]}'
