apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: base-appset
  namespace: argocd
spec:
  generators:
  - git:
      repoURL: https://github.com/slapcat/kubernetes.git
      revision: HEAD
      directories:
      - path: base/*/overlays/prod
