---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: authentik
  namespace: authentik
spec:
  interval: 15m
  timeout: 5m
  chart:
    spec:
      chart: authentik
      version: '2025.10.3'
      sourceRef:
        kind: HelmRepository
        name: authentik
      interval: 5m
  values:
    authentik:
      existingSecret:
        secretName: authentik
        error_reporting:
            enabled: false
    postgresql:
        enabled: true
