---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: authentik
  namespace: authentik
spec:
  interval: 15m
  timeout: 5m
  chart:
    spec:
      chart: authentik
      version: '2025.12.4'
      sourceRef:
        kind: HelmRepository
        name: authentik
        namespace: flux-system
      interval: 5m
  values:
    authentik:
      existingSecret:
        secretName: authentik-secret
        error_reporting:
            enabled: false
    postgresql:
        enabled: true
