---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres
  namespace: guacamole
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: guacamole
  namespace: guacamole
spec:
  storageClassName: "cephfs"
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
