---
apiVersion: v1
kind: Service
metadata:
  name: mariadb
  labels:
    app: mariadb
  annotations:
    metallb.universe.tf/loadBalancerIPs: 10.10.1.101
spec:
  ports:
  - port: 3306
    name: mariadb-port
  selector:
    app: mariadb
  type: LoadBalancer
