kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: zpool-hostpath
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: rawfile.csi.openebs.io
reclaimPolicy: Retain
parameters:
  pvDir: /microk8s
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true
---
allowVolumeExpansion: true
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  annotations:
    meta.helm.sh/release-name: ck-storage
    meta.helm.sh/release-namespace: kube-system
    storageclass.kubernetes.io/is-default-class: "false"
  labels:
    app.kubernetes.io/managed-by: Helm
  name: csi-rawfile-default
provisioner: rawfile.csi.openebs.io
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer

