---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: static-sites
spec:
  storageClassName: manual
  capacity:
    storage: 5Ti
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/srv/sites"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: static-sites-pvc
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Ti
