project: default
source:
  repoURL: https://github.com/slapcat/kubernetes
  path: system/argocd
  targetRevision: main
  directory:
    recurse: true
    jsonnet: {}
destination:
  server: https://kubernetes.default.svc
  namespace: argocd
syncPolicy:
  automated:
    prune: true
    selfHeal: true
    enabled: true
  syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true
