apiVersion: v1
kind: Service
metadata:
  name: argocd-server
spec:
  type: LoadBalancer
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
spec:
  syncPolicy:
    syncOptions:
      - ServerSideApply=true
