name: Docker Image CI

on:
  push:
    branches: [ "main" ]
    paths:
      - '.github/workflows/*.yaml'
      - 'images/**'
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build apache
      run: docker build . --file images/apache-php/Dockerfile --tag apache-php:latest
    - name: Build nextcloud
      run: docker build . --file images/nextcloud-latest/Dockerfile --tag nextcloud:latest
