secretGenerator:
- name: authentik-secret
  namespace: authentik
  envs:
  - authentik.txt
- name: cloudflare-api-secret-token
  namespace: certmanager
  envs:
  - cloudflare-api.txt
- name: guacamole
  namespace: guacamole
  envs:
  - guacamole.txt
- name: mariadb
  namespace: default
  envs:
  - mariadb.txt
- name: opendirectory
  namespace: vm
  files:
  - id_ed25519=opendirectory.txt
- name: openldap-tls
  namespace: default
  files:
  - tls.key=openldap-tls.key
  - tls.crt=openldap-tls.crt
- name: openldap
  namespace: default
  envs:
  - openldap.txt

generatorOptions:
  disableNameSuffixHash: true
